#!/bin/sh -ex

# enable cgi
a2enmod cgi

# remove unrequired webcp icons (all except those named) 
cd /var/www/images
find . -type f ! -name "adminer.png" ! -name "shell.png" ! -name "tab.png" ! -name "webmin.png" -delete
